CREATE TABLE [dbo].[ORDERS]
(
	[ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_ID] [varchar](50) NOT NULL,
	[ITEM_NAME] [varchar](100) NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[CREATED_AT] [datetime] NULL,
	[UPDATED_AT] [datetime] NULL
)

INSERT INTO [ORDERS] (ITEM_ID,ITEM_NAME,QUANTITY)VALUES ('M001','BIRIYANI', 2);