create database HMS_TEST

CREATE TABLE HMS_MENU_TABLE
(
ITEM_ID VARCHAR(50) PRIMARY KEY, --m,s,b
ITEM_NAME VARCHAR(100) NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
PRICE_PER_UNIT DECIMAL(10,2) NOT NULL,
IS_AVAILABLE BIT NOT NULL DEFAULT 1,
CREATED_AT DATETIME DEFAULT GETDATE(),
UPDATED_AT DATETIME DEFAULT GETDATE(),
)

INSERT INTO HMS_MENU_TABLE (ITEM_ID,ITEM_NAME,CATEGORY,PRICE_PER_UNIT)VALUES ('M001','BIRIYANI','M',150.00);
SELECT * FROM HMS_MENU_TABLE