create database HMS_TEST

CREATE TABLE HMS_MENU_TABLE
(
ITEM_ID VARCHAR(50) PRIMARY KEY, --m,s,b
ITEM_NAME VARCHAR(100) NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
PRICE_PER_UNIT DECIMAL(10,2) NOT NULL,
IS_AVAILABLE BIT NOT NULL DEFAULT 1,
CREATED_AT DATETIME DEFAULT GETDATE(),
UPDATED_AT DATETIME DEFAULT GETDATE(),
)

INSERT INTO HMS_MENU_TABLE (ITEM_ID,ITEM_NAME,CATEGORY,PRICE_PER_UNIT)VALUES ('M001','BIRIYANI','M',150.00);
SELECT * FROM HMS_MENU_TABLE


CREATE TABLE HMS_BILLS (
    BILL_ID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMER_NAME NVARCHAR(255) NOT NULL,
    TABLE_NUMBER INT,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    DISCOUNT DECIMAL(10, 2) DEFAULT 0.00,
    TAX_AMOUNT DECIMAL(10, 2) NOT NULL,
    GRAND_TOTAL DECIMAL(10, 2) NOT NULL,
    PAYMENT_STATUS NVARCHAR(50) NOT NULL CHECK (PAYMENT_STATUS IN ('Paid', 'Unpaid', 'Pending')),
    PAYMENT_MODE NVARCHAR(50) CHECK (PAYMENT_MODE IN ('Cash', 'Credit Card', 'Debit Card', 'Online')),
    BILL_DATE DATETIME DEFAULT GETDATE(),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME DEFAULT GETDATE()
);


CREATE TABLE HMS_BILL_ITEMS (
    BILL_ITEM_ID INT PRIMARY KEY IDENTITY(1,1),
    BILL_ID INT NOT NULL,
    ITEM_ID VARCHAR(50) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE_PER_UNIT DECIMAL(10, 2) NOT NULL,
    TOTAL_PRICE AS (QUANTITY * PRICE_PER_UNIT),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    

    CONSTRAINT FK_BillItems_Bill FOREIGN KEY (BILL_ID) REFERENCES HMS_BILLS(BILL_ID),
    
   
    CONSTRAINT FK_BillItems_MenuItem FOREIGN KEY (ITEM_ID) REFERENCES HMS_MENU_TABLE(ITEM_ID)
);




INSERT INTO HMS_BILLS (CUSTOMER_NAME, TABLE_NUMBER, TOTAL_AMOUNT, TAX_AMOUNT, GRAND_TOTAL, PAYMENT_STATUS, PAYMENT_MODE)
VALUES ('John Doe', 5, 300.00, 30.00, 330.00, 'Paid', 'Credit Card');


DECLARE @LastBillId INT = SCOPE_IDENTITY();

INSERT INTO HMS_BILL_ITEMS (BILL_ID, ITEM_ID, QUANTITY, PRICE_PER_UNIT)
VALUES (@LastBillId, 'M001', 2, 150.00);


INSERT INTO HMS_BILLS (CUSTOMER_NAME, TABLE_NUMBER, TOTAL_AMOUNT, TAX_AMOUNT, GRAND_TOTAL, PAYMENT_STATUS)
VALUES ('Jane Smith', 2, 150.00, 15.00, 165.00, 'Unpaid');

SET @LastBillId = SCOPE_IDENTITY();

INSERT INTO HMS_BILL_ITEMS (BILL_ID, ITEM_ID, QUANTITY, PRICE_PER_UNIT)
VALUES (@LastBillId, 'M001', 1, 150.00);